### ISSUE TITLE
Generate new Catalog for Update 53

### ISSUE THREAD

**Issue by cj-zeiger** [GICodeWarrior/fir#11]
We need a new `catalog.json` for update 53, 4 new items were added.

https://foxhole.wiki.gg/wiki/Update_1.53

**Comment by GICodeWarrior** [comment]
Thanks for reaching out!

Can you share a screenshot that isn't working or share some information on how you're accessing the catalog?

The catalog was refreshed for update 53 in commit 1e3182ed58e02fad2b8568ef79bfa88232a65143.
