### ISSUE TITLE
Question Using Pixi for Dependency Management

### ISSUE THREAD

**Issue by gregorywaynepower** [GICodeWarrior/fir#14]
Hey @GICodeWarrior, thanks for creating this.

Would you be open to a pull request with rolling all of the required dependencies into a [pixi.toml file](https://pixi.sh/latest/)? It'll help with managing your dependencies from npm, PyPI, and conda repos if you use those.

It can also resolve dependencies across build platforms as well.

**Comment by GICodeWarrior** [comment]
Thanks for reaching out.

I'm open to build improvements.

What are the advantages of pixi versus the existing dependency management?

**Comment by gregorywaynepower** [comment]
You get faster resolving of dependencies and you're able to add tasks (like running or installing packages via npm) that users can execute via the `pixi shell`. It's pretty similar to the `conda` package manager.

The only issue that I see is so far is that `sed` isn't available for Windows users.

**Comment by GICodeWarrior** [comment]
I'm not understanding the advantages.

Is the goal to run the build natively on Windows?

My understanding is that tensorflow doesn't support GPU acceleration natively on Windows.

**Comment by gregorywaynepower** [comment]
My goal was to roll all of the required dependencies under a package manager that isn't tied to the OS or language ecosystem. I wasn't sure what environments you were developing and running this on which was why I mentioned Windows.

I was just trying to help folks to be able to run the build.sh script without folks having to navigate the complexity of installing package managers to install software from different ecosystems.
