### ISSUE TITLE
Google Analytics?

### ISSUE THREAD

**Issue by DrymarchonShaun** [GICodeWarrior/fir#16]
Not very familiar with the involved languages, but glancing through the code I noticed Google Analytics are referenced a few times, but not mentioned anywhere (ie, README). I was wondering why they're being used?

**Comment by GICodeWarrior** [comment]
I was using it to determine how much the site was being used and which functions were in use. (spoiler: very few people were using the site)

I haven't looked at the metrics in a long while, and I suspect it's broken since Google had an API change recently.

**Comment by GICodeWarrior** [comment]
Feel free to message me on Discord if you have any other questions.
