### ISSUE TITLE
need new training for update 58 (and soon update 59)

### ISSUE THREAD

**Issue by EdWordy** [GICodeWarrior/fir#17]
As the title suggests, new training data is needed.

**Comment by GICodeWarrior** [comment]
I've not been active recently. Can you share the expected release dates?

Do you know if the icon mods are updated yet?

Also, if you or anyone else is interested in learning to train new updates, please ping me on Discord. 🙂

**Comment by Cogsee13** [comment]
Looks like some of them are updated and some of them have been abandoned.

**Comment by GICodeWarrior** [comment]
Thanks to @DarkNomads for the latest update.

Feel free to reach out if you have any questions.
