### ISSUE TITLE
Packaging for the GS Sidebar failed

### ISSUE THREAD

**Issue by archonxgames** [GICodeWarrior/fir#4]
**Issue:** The Google Sheet Sidebar packaging/building failed halfway through.

**Description:** The execution of the build script was stopped after failing to execute a base64 command on a missing file. Is there a missing step in building the gs files or was it not committed?

**Probable Cause:** There are missing files referenced in the build script.

**Steps to Reproduce:** Clone the repository, and run the build script on git bash / wsl terminal. (The instructions in the readme is referencing a potentially outdated file name)

![image](https://user-images.githubusercontent.com/29819192/194743897-c6e6649a-9d27-4e62-8bcd-cee7efd4f6b3.png)

**Comment by GICodeWarrior** [comment]
Please give this a try again, and file a new issue if the problem persists.  Closing as stale for now.
