### ISSUE TITLE
Fails to generate report if screenshot is 1366x768

### ISSUE THREAD

**Issue by Kubuxu** [GICodeWarrior/fir#9]
Through testing with some people, I have discovered that screenshots taken in 1366x768 resolution are not parsed correctly.

Screenshot in question:
![nevish_out1](https://user-images.githubusercontent.com/2259282/226921925-96e22901-9e7b-4f83-9a8a-176372df8eec.png)

Feel free to decide that it is a "won't fix", as there isn't much detail to match icons either way.

**Comment by GICodeWarrior** [comment]
Thanks for sharing.  I've made a change that fixes parsing for this screenshot, and I've added the screenshot to my test cases.

Please give it another try, and let me know how it goes.

Previously, I've only tested as low as 1600x900, so you might find other issues at 1366x768.  Please share another example if you do.

**Comment by Kubuxu** [comment]
Fantastic, the change you made is roughly what I was expecting, I just didn't start digging into the code yet to propose it directly. I will let you know how well it works.

**Comment by Kubuxu** [comment]
Works well from a few tests. If I find any wrongful detections, I will report them to you.
